
import numpy as np
ARENA_SIZE = 100.0 
NUMBER_OF_ROBOTS = 50
STEP_SIZE= 1.0
SENSING_RADIUS = 5.0
NUMBER_OF_STEPS = 2000 #changed from stage 1 : 1.0
RESOURCE_SITE_A  = np.array([75.0, 75.0]) 
RESOURCE_SITE_B  = np.array([25.0, 25.0]) 

RNG_SEED = 42
rng=np.random.default_rng(RNG_SEED)
QUALITY_A = 0.9
QUALITY_B = 0.4

GRID_UNIT = 1.0
DEPOSIT_AMOUNT_A = QUALITY_A * 1.0
DEPOSIT_AMOUNT_B = QUALITY_B * 1.0

EVAPORATION_RATE = 0.02
RECRUITMENT_SCALE = 0.1
ABANDON_RATE = 0.005
GRADIENT_BIAS=0.6
UNDECIDED = 0
SUPPORT_A=1
SUPPORT_B=2
SIZE_OF_GRID= int(ARENA_SIZE/GRID_UNIT)
